GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs?search=sword

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGFuZEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk0ODgwMzUxfQ.4iKKRR4y0gy9GIfPp63CDpPhLgFxZuN82yd5zSQOcAo

{
    "author": "sahand",
    "url": "sahandTest2Blog.com",
    "title": "sahand blog test2",
    "year": 2024
}

### 

DELETE http://localhost:3001/api/blogs/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWltU04iLCJpZCI6MywiaWF0IjoxNjkzODU4NTk4fQ.GaeItPRx8zrmTQBfkXQVUBUpnyp-c75nkwGylpaRsfY

###
PUT http://localhost:3001/api/blogs/16
Content-Type: application/json

{
    "likes": 10
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "sahand",
    "username": "sahand@gmail.com",
    "password": "1234"
}
###
GET http://localhost:3001/api/users/1
###
PUT http://localhost:3001/api/users/sahandSN
Content-Type: application/json

{
    "username": "sahand-sanaei"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "sahand@gmail.com",
    "password": "1234"
}
###
GET http://localhost:3001/api/author
###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "userId": "1"
}