GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs?search=sword

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGFuZHNuQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE2OTYwOTg2MzR9.omE2Y3ABdTWPeCzAitRw_UCh1Gko-E3_-I4LOLZ0Yds

{
    "author": "sahand1",
    "url": "sahandTest1Blog.com",
    "title": "sahand blog test1"
}

### 

DELETE http://localhost:3001/api/blogs/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGFuZEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk2MDY4OTU4fQ.IhmjOzAMM5t452_i0qK01Fu9PIW391ojgg0pR5U5gik

###
PUT http://localhost:3001/api/blogs/16
Content-Type: application/json

{
    "likes": 10
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "sahand",
    "username": "sahandsn@gmail.com",
    "password": "1234"
}
###
GET http://localhost:3001/api/users/1
###
PUT http://localhost:3001/api/users/sahandSN
Content-Type: application/json

{
    "username": "sahand-sanaei"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "sahandsn@gmail.com",
    "password": "1234"
}
###
GET http://localhost:3001/api/author
###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "userId": "1",
    "blogId": "2"
}
###
PUT http://localhost:3001/api/readinglists/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGFuZHNuQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE2OTYxMTIwOTEsImV4cCI6MTY5NjExMjE1MX0._p-GudSL-0ug2hkS7MuXR8edGJfjIbZkx4uR53_5xE0

{
    "read": true
}
###
DELETE http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGFuZHNuQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE2OTYxMTIwOTEsImV4cCI6MTY5NjExMjE1MX0._p-GudSL-0ug2hkS7MuXR8edGJfjIbZkx4uR53_5xE0