GET http://localhost:3001/api/blogs/

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "author": "joe bd jr",
    "url": "joeJrBlog.com",
    "title": "joeJr blog"
}

### 

DELETE http://localhost:3001/api/blogs/99
###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
    "like": 7
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "joe",
    "username": "joeBD",
    "password": "1234"
}
###
GET http://localhost:3001/api/users
###
PUT http://localhost:3001/api/users/sahandSN
Content-Type: application/json

{
    "username": "sahand-sanaei"
}